In [15]:
import pickle

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np


In [16]:

data_dict = pickle.load(open('./data.pickle', 'rb'))

data = np.asarray(data_dict['data'])
labels = np.asarray(data_dict['labels'])

x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, shuffle=True, stratify=labels)

In [17]:
model = RandomForestClassifier()

In [18]:
model.fit(x_train, y_train)

RandomForestClassifier()

In [19]:
preds = model.predict(x_test)

In [20]:
preds

array([23, 24, 21,  9, 24, 16, 24, 21,  3, 25, 16, 22,  6, 19, 18,  2, 21,
        0,  2, 20, 12,  4, 25,  4, 25, 16,  9,  8, 15,  4, 15,  6, 17,  6,
       13, 18, 22, 11,  1,  6,  7, 25,  0,  0,  4, 24, 15, 14, 24,  5, 17,
        7, 24, 10, 23,  5,  9,  9, 15,  3,  6,  9, 10, 20, 25, 24, 25, 15,
       10, 13, 13, 13, 24, 11,  9, 12,  1,  2,  9, 23, 16, 23, 12,  8, 18,
       23,  4, 19,  6, 25, 21, 22,  9, 13,  5, 23, 11,  0, 14, 10,  6,  4,
       18, 20, 23, 19, 17,  1,  5, 19, 12, 13,  7, 13,  7, 16,  9, 22, 15,
        3,  5, 17,  7,  2, 13, 10, 20,  6, 18,  5, 18,  1, 16, 19,  0, 12,
       21,  1,  8, 20,  4,  8, 23, 21, 11, 14, 15, 21,  3,  1, 25, 17, 13,
        2, 22, 25, 16,  8, 14,  0,  3,  1,  7,  4,  2, 22, 13,  7, 11,  8,
       13,  7, 17, 23, 13,  8, 18, 21,  4,  3, 22, 20,  1, 14, 15,  9,  6,
        0,  2, 14,  0, 21, 21,  4, 15, 22, 25, 13, 18, 16, 24,  7,  2, 23,
        3, 21, 16, 24, 20, 10,  4, 23,  6, 15, 11,  8, 11, 16, 11, 22, 21,
       10, 19,  7, 18, 20

In [21]:
y_test

array([23, 24, 21,  9, 24, 16, 24, 21,  3, 25, 16, 22,  6, 19, 18,  2, 21,
        0,  2, 20, 12,  4, 25,  4, 25, 16,  9,  8, 15,  4, 15,  6, 17,  6,
       13, 18, 22, 11,  1,  6,  7, 25,  0,  0,  4, 24, 15, 14, 24,  5, 17,
        7, 24, 10, 23,  5,  9,  9, 15,  3,  6,  9, 10, 20, 25, 24, 25, 15,
       10, 13, 13, 13, 24, 11,  9, 12,  1,  2,  9, 23, 16, 23, 12,  8, 18,
        7,  4, 19,  6, 25, 21, 22,  9, 13,  5, 23, 11,  0, 14, 10,  6,  4,
       18, 20, 23, 19, 17,  1,  5, 19, 12, 13,  7, 13,  7, 16,  9, 22, 15,
        3,  5, 17,  7,  2, 13, 10, 20,  6, 18,  5, 18,  1, 16, 19,  0, 12,
       21,  1,  8, 20,  4,  8, 23, 21, 11, 14, 15, 21,  3,  1, 25, 17, 13,
        2, 22, 25, 16,  8, 14,  0,  3,  1,  7,  4,  2, 22, 13,  7, 11,  8,
       13,  7, 17, 23, 13,  8, 18, 21,  4,  3, 22, 20,  1, 14, 15,  9,  6,
        0,  2, 14,  0, 21, 21,  4, 15, 22, 25, 13, 18, 16, 24,  7,  2, 23,
        3, 21, 16, 24, 20, 10,  4, 23,  6, 15, 11,  8, 11, 16, 11, 22, 21,
       10, 19,  7, 18, 20

In [22]:
model.predict([x_train[34]])

array([10])

In [23]:
y_train[34]

10

In [24]:
import pickle
pickle.dump(model, open('model.pkl', 'wb'))



In [11]:
y_train[0]

0

In [12]:
x_train

array([[0.2997117 , 0.67563486, 0.33459902, ..., 0.55886769, 0.2892105 ,
        0.56647629],
       [0.24601603, 0.64924216, 0.27837169, ..., 0.42463034, 0.26553169,
        0.43245813],
       [0.21100934, 0.76648521, 0.23857364, ..., 0.6790632 , 0.19062477,
        0.70732856],
       ...,
       [0.34269109, 0.76812989, 0.36292836, ..., 0.75141686, 0.32173595,
        0.76599872],
       [0.1429234 , 0.93787867, 0.18116061, ..., 0.77141988, 0.11641958,
        0.80851132],
       [0.20911045, 0.84507978, 0.25232548, ..., 0.73443151, 0.18951336,
        0.77210903]])

In [14]:
model.score(x_test, y_test)

0.9961538461538462